name = "javault"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "production"
CF_PROXY_URL = "https://javault.tuchiha675.workers.dev/v2?url="
BACKEND_URL = "https://javault.onrender.com"

# Scheduled events for job processing
[triggers]
crons = ["*/5 * * * *"]

# For development/fallback values (these will be overridden by secrets in production)
[env.development]
vars = { INTERNAL_API_KEY = "dev-key-placeholder" }
